### Vorhandenes Comicheft aktualisieren
PUT {{restUrl}}/00000000-0000-0000-0000-000000000040
Content-Type: application/json
If-Match: "0"

< .\json\comicheft-40-put.json

### NICHT-Vorhandenes Comicheft aktualisieren
PUT {{restUrl}}/99999999-9999-9999-9999-999999999999
Content-Type: application/json
If-Match: "0"

< .\json\comicheft-40-put.json