### Neues Comicheft anlegen
POST {{restUrl}}
Content-Type: application/json

< .\json\comicheft-neu.json

### Neues Comicheft anlegen, aber der Titel existiert bereits
POST {{restUrl}}
Content-Type: application/json

< .\json\comicheft-neu.titel-exists.json