//
// N e t z w e r k   -   V e r b i n d u n g   n o t w e n d i g
//

// siehe auch https://studio.apollographql.com/sandbox/explorer

### Suche id, version und titel von allen Comicheften
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  comichefte {
    id
    version
    art
    titel {
      titel
    }
  }
}

### Suche isbn, version, art und titel von einem Comicheft mit vorhandener Comicheft-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "1") {
  comicheft(id: $id) {
    isbn
    version
    art
    titel {
      titel
    }
  }
}

{
  "id": "1"
}

### Suche titel von einem Comicheft mit nicht-vorhandener Comicheft-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "999999") {
  comicheft(id: $id) {
    titel {
      titel
    }
  }
}

{
  "id": "999999"
}

### Suche art von Comicheften mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "Alpha") {
  comichefte(titel: $titel) {
    art
  }
}

{
  "titel": "Alpha"
}

### Suche art, schlagwoerter und titel von Comicheften mit vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "a") {
  comichefte(titel: $titel) {
    art
    schlagwoerter
    titel {
      titel
    }
  }
}

{
  "titel": "a"
}

### Suche art von Comicheften mit NICHT-vorhandenem Titel
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($titel: String = "Nichtvorhanden") {
  comichefte(titel: $titel) {
    art
  }
}

{
  "titel": "Nichtvorhanden"
}
