### Suche id, titel, art und version von allen Comicheften
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

{
  comichefte {
    id
    titel
    art
    version
  }
}

### Suche titel, art, isbn und version von einem Comicheft mit vorhandener Comicheft-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "00000000-0000-0000-0000-000000000001") {
  comicheft(id: $id) {
    titel
    art
    isbn
    version
  }
}

{
  "id": "00000000-0000-0000-0000-000000000001"
}

### Suche titel von einem Comicheft mit nicht-vorhandener Comicheft-ID
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query ($id: ID! = "99999999-9999-9999-9999-999999999999") {
  comicheft(id: $id) {
    titel
  }
}

{
  "id": "99999999-9999-9999-9999-999999999999"
}
