### Neues Comicheft anlegen
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      titel: "Testgraphql",
      rating: 1,
      art: KINDLE,
      verlag: ZEIT_VERLAG,
      preis: 5.9,
      rabatt: 0.1,
      lieferbar: true,
      datum: "2022-01-31",
      isbn: "3897225832",
      homepage: "http://test.de/",
      schlagwoerter: ["JAVASCRIPT"]
    }
  )
}

### Neues Comicheft mit ungueltigen Daten anlegen
POST {{graphQlUrl}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  create(
    input: {
      titel: "?!$",
      rating: 999,
      art: KINDLE,
      verlag: ZEIT_VERLAG,
      preis: -999,
      rabatt: 999,
      lieferbar: true,
      datum: "123",
      isbn: "123",
      homepage: "?!$",
      schlagwoerter: ["JAVASCRIPT"]
    }
  )
}
